[build]
target = "aarch64-unknown-linux-gnu"

[env]
CC_aarch64_unknown_linux_gnu = "aarch64-unknown-linux-gnu-gcc"
CXX_aarch64_unknown_linux_gnu = "aarch64-unknown-linux-gnu-g++"
AR_aarch64_unknown_linux_gnu = "aarch64-unknown-linux-gnu-ar"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-unknown-linux-gnu-gcc"
